@startuml "CU - 4 - Registro de usuario"

left to right direction

/' === Sección de actores === '/
actor "     Usuario \nadministrador" as admin
package "Personal del hospital" {
    actor "Usuario" as usuario
}

/' === Sección de elementos === '/
package "Registro de usuarios" {
    usecase "Ingresar a la sección de registro de usuarios" as UC1
    usecase "Ingresar a la sección de actualización de usuarios" as UC2
    usecase "Ingresar datos identificadores del usuario" as UC3
    usecase "Ingresar datos del usuario" as UC4
    usecase "Asignar contraseña inicial" as UC5
    usecase "Cambiar contraseña" as UC6
    usecase "Guardar usuario" as UC7
}

(Validar Campos) as validar
(Validar Campos) as validar2
(Impedir Registro) as denegar
(Consultar Usuario) as comprobar
(Registrar Usuario) as registrar
(Registrar Usuario) as registrar2

/' === Sección de Relaciones === '/
admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
admin --> UC5
admin --> UC7

UC3 ..> comprobar : <<include>>
comprobar <.. denegar : <<extends>>

UC7 ..> validar : <<include>>
validar <.. registrar : <<extends>>

usuario --> UC6
UC6 ..> validar2 : <<include>> 
validar2 <.. registrar2 : <<extends>>

@enduml