@startuml "CU - 5 - Ordenar Expedientes"

left to right direction

/' === Sección de actores === '/
actor "   Usuario \nenfermero" as enfermero

/' === Sección de elementos === '/
package "Asignar orden de atención" {
    usecase "Listar expedientes" as UC0
    usecase "Establecer número de orden para atención" as UC1
    usecase "Asigar especialización" as UC2
}

(Cargar expedientes) as cargar
(Comprobar que no se cruce el No. Orden) as revisar

/' === Sección de Relaciones === '/
enfermero --> UC0
enfermero --> UC1
enfermero --> UC2

UC0 <.. cargar : <<extends>>
UC2 ..> revisar : <<include>>

@enduml