@startuml "CU - 4 - Gestión de Usuarios - Administrador"

left to right direction

/' === Sección de jerarquias === '/
actor "Usuario Super Administrador" as sadmin1
actor "Usuario Administrador" as admin1
actor "Usuario Empleado" as user1
sadmin1 --> admin1
admin1 --> user1

/' === Sección de actores === '/
actor "Usuario Administrador" as admin

/' === Sección de elementos === '/
package "Módulo Usuarios" {
    usecase "Crear Usuario" as user_create
    usecase "Editar Usuario" as user_edit
    usecase "Bloquear Usuario" as user_block
    usecase "Asignar Rol a Usuario" as user_assign_role
    usecase "Asignar Dependencia a Usuario" as user_assign_dep
    usecase "Actualizar Contraseña (Aleatoria)" as user_update_password
}

/' === Sección de Relaciones === '/
admin --> user_create
admin --> user_edit
admin --> user_block
admin --> user_assign_role
admin --> user_assign_dep
admin --> user_update_password

@enduml
