@startuml "CU - 3 - Gestión de Dependencias - Administrador"

left to right direction

/' === Sección de jerarquias === '/
actor "Usuario Super Administrador" as sadmin1
actor "Usuario Administrador" as admin1
actor "Usuario Empleado" as user1
sadmin1 --> admin1
admin1 --> user1

/' === Sección de actores === '/
actor "Usuario Administrador" as admin

/' === Sección de elementos === '/
package "Módulo Dependencias" {
    usecase "Ingresar Dependencia" as dep_create
    usecase "Editar Dependencia" as dep_edit
}

/' === Sección de Relaciones === '/
admin --> dep_create
admin --> dep_edit

@enduml
