@startuml "Diagrama de secuencia 1 - Autenticación de usuario"

actor "Usuario" as User
participant "Breeze" as B
participant "Laravel" as L
participant "Spatie" as S

User -> B: Solicitud de inicio de sesión/registro
B -> L: Manejar inicio de sesión/registro
L -> B: Devolver estado de autenticación

alt Autenticado
    B -> User: Devolver respuesta exitosa

    User -> L: Solicitud de recurso
    L -> S: Verificar permisos
    alt Tiene permiso
        S -> L: Permitir acceso
        L -> User: Proporcionar recurso
    else No tiene permiso
        S -> L: Denegar acceso
        L -> User: Devolver acceso denegado
    end
else Autenticación fallida
    B -> User: Devolver respuesta de error
end
@enduml
